Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-20.04"

  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 4
  end

  config.vm.provider "vmware_desktop" do |v, override|
    override.vm.box = "bytesguy/ubuntu-server-20.04-arm64"
  end

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "8192"
    v.vmx["numvcpus"] = "4"
  end

  config.vm.network "public_network", ip: "192.168.1.30"

  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end
end
