Vagrant.configure("2") do |config|
  config.vm.box = "bytesguy/debian-10-arm64"
  config.vm.box_version = "1.0.0"
  config.vm.provider :vmware_desktop do |vmware|
    vmware.vmx["ethernet0.pcislotnumber"] = "33"
  end
end
