Vagrant.configure("2") do |config|

  config.vm.box = "bento/debian-12"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
    v.gui = false
  end

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
    v.gui = false
  end

  config.vm.network "public_network"
end
